[package]
name = "lay"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.21"
ring = "0.16"

[workspace]
members = ["relay-client", "relay-server"]
